// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChCwoHk09nWue22q1Dg2iT5eNbXWNW4EQ',
    appId: '1:405790350389:web:55a022699d248b9d0ea57c',
    messagingSenderId: '405790350389',
    projectId: 'restaurant-c1447',
    authDomain: 'restaurant-c1447.firebaseapp.com',
    storageBucket: 'restaurant-c1447.appspot.com',
    measurementId: 'G-580PXF2S3T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCx7HX-U909O67t02DwpjaYb05nGBYPvyI',
    appId: '1:405790350389:android:09022e2aaaf6e0780ea57c',
    messagingSenderId: '405790350389',
    projectId: 'restaurant-c1447',
    storageBucket: 'restaurant-c1447.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPz-jRB6d_uQLkibQFBie99Kci-m4r1y8',
    appId: '1:405790350389:ios:1731886cb79e1c1a0ea57c',
    messagingSenderId: '405790350389',
    projectId: 'restaurant-c1447',
    storageBucket: 'restaurant-c1447.appspot.com',
    iosBundleId: 'com.example.restaurantApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPz-jRB6d_uQLkibQFBie99Kci-m4r1y8',
    appId: '1:405790350389:ios:1731886cb79e1c1a0ea57c',
    messagingSenderId: '405790350389',
    projectId: 'restaurant-c1447',
    storageBucket: 'restaurant-c1447.appspot.com',
    iosBundleId: 'com.example.restaurantApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChCwoHk09nWue22q1Dg2iT5eNbXWNW4EQ',
    appId: '1:405790350389:web:bfbc4bc4fa20847e0ea57c',
    messagingSenderId: '405790350389',
    projectId: 'restaurant-c1447',
    authDomain: 'restaurant-c1447.firebaseapp.com',
    storageBucket: 'restaurant-c1447.appspot.com',
    measurementId: 'G-74CBW0QLKN',
  );
}
